apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - rancher.audryus.arpa
