apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cert
  namespace: argo
spec:
  secretName: argo-tls-secret
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - argo.audryus.arpa
